# =========================================================
# 1. DIZIONARI, PILLS E DATABASE CENTRALIZZATO
# =========================================================
COPPIE_INCOMPATIBILI = [
    {"Statico", "Antisismico"}, {"Angolo aperto", "Angolo chiuso"},
    {"Portante", "Non portante"}, {"Singolo", "Doppio"},
    {"Per ripiano in vetro", "Per ripiano in legno"}, {"Con serratura", "Senza serratura"},
    {"Passo 25", "Passo 50"}, {"L50", "L55"}, {"Scorrevoli", "A saracinesca"},
    {"Per attacco montante", "Per attacco fiancata"}, {"Superiore", "Tra ripiani di base"},
    {"Dritto", "Inclinato"}, {"Cromato", "Verniciato"},
    {"Multibarra", "Multilame", "In rete"}, {"Profilo a L", "Profilo a U"},
    {"Per ripiano di base", "Per fiancata"}, {"Terminale", "Centrale"},
    {"Liscio", "Liscia", "Forato", "Forata", "In filo"}, {"Zincato", "Verniciata"}
]

GLOSSARIO_TECNICO = {
    "mensola": "BRACKET", "mensole": "BRACKETS", "gondola": "GONDOLA",
    "spalla": "FRAME", "innesto": "COUPLING", "montante": "UPRIGHT",
    "per": "FOR", "losanga": "LOSANGA", "cancelletto": "GATE", "vasca": "TANK"
}

SUB_OPTIONS_CONFIG = {
    "VPA (+)": {"Serie S": "S SERIES", "Serie SS": "SS SERIES", "Serie M": "M SERIES", "Serie L": "L SERIES"},
    "Con distanziale (+)": {"L100": "S100", "L150": "S150", "L200": "S200", "L250": "S250"},
    "Numero diagonali (+)": {"Doppie": "DD", "Triple": "TD", "Quadruple": "QD"},
    "Sezione montante (+)": {"L55": "L55", "L80 Z/S": "L80 Z/S", "L80 Z/M": "L80 Z/M", "L100 Z/S": "L100 Z/S", "L100 Z/M": "L100 Z/M", "L120 Z/S": "L120 Z/S", "70X30": "70X30", "90X30": "90X30", "30X30": "30X30"},
    "Tipologia di mensola (+)": {"Mensola saldata a filo superiore": "UPPER BRACKET", "Mensola saldata a filo inferiore": "LOWER BRACKET"},
    "Compatibilità piede di base (+)": {"Per piede H90": "FOR H90 BASE FOOT", "Per piede H100": "FOR H100 BASE FOOT", "Per piede H150": "FOR H150 BASE FOOT"},
    "Attacco gancio (+)": {"Attacco barra": "HOOK FOR BAR", "Attacco multilame": "HOOK FOR MULTISTRIP", "Attacco pannello forato": "HOOK FOR SLOTTED PANEL"},
    "Orientamento Destro / Sinistro (+)": {"Destra": "RIGHT", "Sinistra": "LEFT"},
    "Posizioni multiple (+)": {"1 posizione": "1 POSITION", "2 posizioni": "2 POSITIONS", "3 posizioni": "3 POSITIONS"},
    "Altezza piede (+)": {"H90": "H90", "H100": "H100", "H150": "H150"},
    "Predisposto per montante (+)": {"L80": "FOR L80 UPRIGHT", "L100/L120": "FOR L100/L120 UPRIGHT"},
    "Numero tasche (+)": {"1 Tasca": "1 POCKET", "2 Tasche": "2 POCKETS"},
    "Numero gradoni (+)": {"1 gradone": "1 STEP", "2 gradoni": "2 STEPS", "3 gradoni": "3 STEPS"},
    "Asimmetrica (+)": {"AS240": "AS240", "AS340": "AS340", "AS440": "AS440"}
}

EXTRA_CON_INPUT_MANUALE = ["Sezione circolare", "Sezione quadrata"]

MATERIALI_CONFIG = {
    "METAL COMP": {"METAL": "METAL", "ZINCATO": "GALVANIZED", "INOX": "STAINLESS STEEL", "ALLUMINIO": "ALUMINIUM"},
    "WOOD COMP": {"LAMINATO": "LAMINATED", "NOBILITATO": "MELAMINE", "TRUCIOLARE": "CHIPBOARD", "OBS": "OSB", "HPL": "HPL"},
    "PLASTIC COMP": {"PLX": "PLX", "POLICARBONATO": "POLYCARBONATE", "PVC": "PVC", "GOMMA": "RUBBER"},
    "GLASS COMP": {"VETRO TEMPRATO": "TEMPERED", "VETRO SATINATO": "SATIN"},
    "FASTENER": {"NERO": "", "ZINCATO": "GALVANIZED", "BRUNITO": "BURNISHED"},
    "ASSEMBLY": {}
}

# --- GRUPPI DI PILLS ISOLATI ---
PILLS_METAL_COMP = {
    "Altezza piede (+)": "",
    "Angolo aperto": "EXTERNAL CORNER",
    "Angolo chiuso": "INNER CORNER",
    "Antisgancio": "ANTI-RELEASE",
    "Asolato": "SLOTTED",
    "Attacco a pinza": "GRIPPED",
    "Attacco a saracinesca": "SHUTTER",
    "Attacco a seggiola": "L-SHAPED PROFILE",
    "Attacco gancio (+)": "",
    "Attacco montante": "HOOK ONTO UPRIGHT",
    "Centrale": "CENTRAL",
    "Colorato": "COLORED",
    "Compatibilità piede di base (+)": "",
    "Completa di paracolpo ABS": "WITH ABS BUFFER",
    "Con asola centrale": "WITH CENTRAL SLOT",
    "Con collegamento superiore": "WITH UPPER CONNECTION",
    "Con componente saldato": "WITH WELDED ELEMENT",
    "Con distanziale (+)": "WITH SPACER",
    "Con finestra": "WITH WINDOW",
    "Con foro serratura": "WITH LOCK HOLE",
    "Con guide RAM": "WITH RAM GUIDE",
    "Con illuminazione": "WITH LIGHTING",
    "Con inserti filettati": "WITH RIVET",
    "Con mensole": "WITH BRACKET",
    "Con mensole saldate": "WITH WELDING BRACKET",
    "Con piega frontale": "WITH DOWNWARD",
    "Con portaprezzo": "WITH TICKET-HOLDER",
    "Con rinforzo": "REINFORCED",
    "Con ruote": "WITH WHEELS",
    "Con scasso": "WITH RECESS",
    "Con serratura": "WITH LOCK",
    "Con tasca oscillante": "WITH LIFT-UP POCKET",
    "Con viteria": "WITH SCREWS",
    "Con viteria saldata": "WITH WELDING SCREWS",
    "Cromato": "CHROMED",
    "Di collegamento": "CONNECTING",
    "Doppio": "DOUBLE",
    "Dritto": "STRAIGHT",
    "Forato": "PERFORATED",
    "Gondola": "GONDOLA",
    "Illuminato": "ILLUMINATED",
    "Impilabile": "STACKABLE",
    "In filo": "WIRE",
    "In rete": "MESH",
    "Inclinata": "INCLINED",
    "Inclinato": "SLOPING",
    "Liscio": "PLAIN",
    "Minirack": "MINIRACK",
    "Multibarra": "MULTIBAR",
    "Multilame": "MULTISTRIP",
    "Nervata": "RIBBED",
    "Nervato": "RIBBED",
    "Non portante": "NON LOAD-BEARING",
    "Numero diagonali (+)": "",
    "Orientamento Destro / Sinistro (+)": "",
    "Passo 25": "PITCH 25",
    "Passo 50": "PITCH 50",
    "Per attacco fiancata": "HOOK ONTO SIDE-PANEL",
    "Per controventatura": "FOR CROSS-WALL",
    "Per crociera verticale": "FOR VERTICAL CROSS-WALL",
    "Per fiancata": "FOR SIDE PANEL",
    "Per montante M70": "FOR M70 UPRIGHT",
    "Per montante M90": "FOR M90 UPRIGHT",
    "Per ripiano": "FOR SHELF",
    "Per ripiano di base": "FOR BASE SHELF",
    "Per ripiano in legno": "FOR WOODEN SHELF",
    "Per ripiano in vetro": "FOR GLASS SHELF",
    "Per Top legno": "FOR TOP SHELF",
    "Piegato": "BENT",
    "Piegato-saldato": "BENT AND WELDED",
    "Portante": "LOAD-BEARING",
    "Posizioni multiple (+)": "",
    "Predisposto per montante (+)": "",
    "Predisposto per portaprezzo": "ACCEPTS TICKET-HOLDER",
    "Profilo a L": "L-SHAPED",
    "Profilo a U": "U-SHAPED",
    "Regolabile": "ADJUSTABLE",
    "Rinforzata": "REINFORCED",
    "Rovescio": "REVERSE",
    "Sagomata": "SHAPED",
    "Saldata": "WELDED",
    "Scantonato": "NOTCHED",
    "Scorrevoli": "SLIDING",
    "Semicircolare": "SEMICIRCULAR",
    "Senza serratura": "WITHOUT LOCK",
    "Serigrafata": "SILKSCREENED",
    "Sezione montante (+)": "",
    "Sezione a C": "C-PROFILE",
    "Sezione circolare": "CIRCULAR SECTION",
    "Sezione quadrata": "SQUARE SECTION",
    "Singolo": "SINGLE",
    "Statico": "STATIC",
    "Stondata": "ROUNDED",
    "Su due livelli": "TWO LEVELS",
    "Su ruote": "ON WHEELS",
    "Superiore": "TOP",
    "Terminale": "END",
    "Tipologia di mensola (+)": "",
    "Tra ripiani di base": "INTER-BASE SHELF",
    "Trapezoidale": "SLOPING",
    "Trasparente": "TRANSPARENT",
    "Verniciato": "PAINTED",
    "VPA (+)": "VPA"
}

PILLS_WOOD_COMP = {
    "Altezza piede (+)": "",
    "Asolato": "SLOTTED",
    "Attacco a pinza": "GRIPPED",
    "Attacco a saracinesca": "SHUTTER",
    "Attacco a seggiola": "L-SHAPED PROFILE",
    "Attacco gancio (+)": "",
    "Attacco montante": "HOOK ONTO UPRIGHT",
    "Bordi smussati": "CHAMFERED EDGES",
    "Centrale": "CENTRAL",
    "Compatibilità piede di base (+)": "",
    "Completa di paracolpo ABS": "WITH ABS BUFFER",
    "Con asola centrale": "WITH CENTRAL SLOT",
    "Con collegamento superiore": "WITH UPPER CONNECTION",
    "Con finestra": "WITH WINDOW",
    "Con foro serratura": "WITH LOCK HOLE",
    "Con inserti filettati": "WITH RIVET",
    "Con lati bordati": "WITH EDGED SIDES",
    "Con mensole": "WITH BRACKET",
    "Con ruote": "WITH WHEELS",
    "Con scasso": "WITH RECESS",
    "Con serratura": "WITH LOCK",
    "Con tasca oscillante": "WITH LIFT-UP POCKET",
    "Con viteria": "WITH SCREWS",
    "Di collegamento": "CONNECTING",
    "Doppio": "DOUBLE",
    "Dritto": "STRAIGHT",
    "Forato": "PERFORATED",
    "Fresata": "MILLING",
    "Gondola": "GONDOLA",
    "Orientamento Destro / Sinistro (+)"
}

PILLS_PLASTIC_COMP = {
    "Adesivo": "ADHESIVE",
    "Antiurto": "SHOCKPROOF",
    "Asolato": "SLOTTED",
    "Attacco a pinza": "GRIPPED",
    "Attacco a saracinesca": "SHUTTER",
    "Attacco a seggiola": "L-SHAPED PROFILE",
    "Attacco gancio (+)": "",
    "Attacco montante": "HOOK ONTO UPRIGHT",
    "Bordi smussati": "CHAMFERED EDGES",
    "Centrale": "CENTRAL",
    "Con asola centrale": "WITH CENTRAL SLOT",
    "Con finestra": "WITH WINDOW",
    "Con foro serratura": "WITH LOCK HOLE",
    "Con mensole": "WITH BRACKET",
    "Con ruote": "WITH WHEELS",
    "Con scasso": "WITH RECESS",
    "Con serratura": "WITH LOCK",
    "Con viteria": "WITH SCREWS",
    "Di collegamento": "CONNECTING",
    "Doppio": "DOUBLE",
    "Dritto": "STRAIGHT",
    "Forato": "PERFORATED",
    "Orientamento Destro / Sinistro (+)": ""
}

PILLS_GLASS_COMP = {
    "Antiurto": "SHOCKPROOF",
    "Asolato": "SLOTTED",
    "Attacco a pinza": "GRIPPED",
    "Attacco a saracinesca": "SHUTTER",
    "Attacco a seggiola": "L-SHAPED PROFILE",
    "Attacco gancio (+)": "",
    "Attacco montante": "HOOK ONTO UPRIGHT",
    "Bordi smussati": "CHAMFERED EDGES",
    "Centrale": "CENTRAL",
    "Con asola centrale": "WITH CENTRAL SLOT",
    "Con finestra": "WITH WINDOW",
    "Con foro serratura": "WITH LOCK HOLE",
    "Con mensole": "WITH BRACKET",
    "Con ruote": "WITH WHEELS",
    "Con scasso": "WITH RECESS",
    "Con serratura": "WITH LOCK",
    "Con viteria": "WITH SCREWS",
    "Di collegamento": "CONNECTING",
    "Doppio": "DOUBLE",
    "Dritto": "STRAIGHT",
    "Forato": "PERFORATED",
    "Orientamento Destro / Sinistro (+)": ""
}

PILLS_FASTNER = {
    "Autobloccante": "SELF-LOCKING",
    "Autoperforanti": "SELF-DRILLING",
    "Con testa": "WITH HEAD",
    "Dentellata": "SERRATED LOCK",
    "Elastica": "GROWER",
    "Fascia Larga": "WIDE BAND",
    "Flangiato": "FLANGED",
    "Senza testa": "WITHOUT HEAD",
    "Testa Bombata": "ROUND HEAD",
    "Testa a croce": "CROSS HEAD",
    "Testa esagonale": "HEX HEAD",
    "Testa esagono incassato": "HEXAGON SOCKET HEAD",
    "Testa svasata": "COUNTERSUNK HEAD"
}

PILLS_ASSEMBLY = {
    "Altezza piede (+)": "",
    "Angolo aperto": "EXTERNAL CORNER",
    "Angolo chiuso": "INNER CORNER",
    "Antisgancio": "ANTI-RELEASE",
    "Antisismico": "SEISMIC-RESISTANT",
    "Asimmetrica (+)": "",
    "Attacco a seggiola": "L-SHAPED PROFILE",
    "Attacco montante": "ONTO THE UPRIGHT",
    "Centrale": "CENTRAL",
    "Colorato": "COLORED",
    "Compatibilità piede di base (+)": "",
    "Completa di paracolpo ABS": "WITH ABS BUFFER",
    "Con ante scorrevoli": "WITH SLIDING DOOR",
    "Con asola centrale": "WITH CENTRAL SLOT",
    "Con batticarrello": "WITH TROLLEY BEATER",
    "Con collegamento superiore": "WITH UPPER CONNECTION",
    "Con componente saldato": "WITH WELDED ELEMENT",
    "Con distanziale (+)": "WITH SPACER",
    "Con finestra": "WITH WINDOW",
    "Con foro serratura": "WITH LOCK HOLE",
    "Con ganci": "WITH HOOKS",
    "Con guide RAM": "WITH RAM GUIDE",
    "Con illuminazione": "WITH LIGHTING",
    "Con inserti filettati": "WITH RIVET",
    "Con lati bordati": "WITH EDGED SIDES",
    "Con macchine di pagamento": "WITH GLORY MACHINES PAYMENT",
    "Con mensole": "WITH BRACKET",
    "Con mensole saldate": "WITH WELDED BRACKETS",
    "Con portaprezzo": "WITH TICKET-HOLDER",
    "Con portaprezzo in filo": "WITH PRICE-HOLDER WIRE",
    "Con rete divisoria": "WITH DIVIDING NET",
    "Con rinforzo": "REINFORCED",
    "Con ripiani": "WITH SHELF",
    "Con ripiani inclinati": "WITH INCLINED SHELF",
    "Con ruote": "WITH WHEELS",
    "Con scasso": "WITH RECESS",
    "Con serratura": "WITH LOCK",
    "Con tasca oscillante": "WITH LIFT-UP POCKET",
    "Con viteria": "WITH SCREWS",
    "Con viteria saldata": "WITH WELDING SCREWS",
    "Cromato": "CHROMED",
    "Di collegamento": "CONNECTING",
    "Doppio": "DOUBLE",
    "Dritto": "STRAIGHT",
    "Forato": "PERFORATED",
    "Gondola": "GONDOLA",
    "Mobile": "MOBILE",
    "Numero diagonali (+)": "",
    "Numero gradoni (+)": "",
    "Numero tasche (+)": "",
    "Orientamento Destro / Sinistro (+)": "",
    "Per alimenti": "FOR FOOD",
    "Per casse automatiche": "FOR SELF PAY",
    "Rotante": "ROTATING",
    "Sezione montante (+)": "",
    "Terminale": "END",
    "Verniciata": "POWDER COATED",
    "Zincato": "GALVANIZED"
}

# Mappa di associazione tra la macro-categoria e il suo dizionario di pills specifico
MAPPA_PILLS_CATEGORIA = {
    "METAL COMP": PILLS_METAL_COMP,
    "WOOD COMP": PILLS_WOOD_COMP,
    "PLASTIC COMP": PILLS_PLASTIC_COMP,
    "GLASS COMP": PILLS_GLASS_COMP,
    "FASTENER": PILLS_FASTNER,
    "ASSEMBLY": PILLS_ASSEMBLY
}

DATABASE = {
    "METAL COMP": {
        "macro_en": "METAL COMPONENT",
        "Particolari": {
            "Adattatore": ["ADAPTER", "PILLS_METAL_COMP", "ADAPTER"],
            "Anta/sportello": ["DOOR", "PILLS_METAL_COMP", "DOOR"],
            "Canalina passa cavi": ["CABLE TRAY", "PILLS_METAL_COMP", "ESA"],
            "Cassetto estraibile": ["PULL-OUT DRAWER", "PILLS_METAL_COMP", "DRAWER"],
            "Cesto in filo": ["WIRE-BASKET", "PILLS_METAL_COMP", "BASKET"],
            "Chiusura": ["COVER", "PILLS_METAL_COMP", "COVER"],
            "Cielino": ["CANOPY", "PILLS_METAL_COMP", "CANOPY"],
            "Compensazione": ["FILLER PIECE", "PILLS_METAL_COMP", "SPACER"],
            "Controventatura": ["BRACING", "PILLS_METAL_COMP", "BRACING"],
            "Coprimontante": ["UPRIGHT-COVER", "PILLS_METAL_COMP", "COVER"],
            "Copripiede": ["FOOT COVER", "PILLS_METAL_COMP", "COVER"],
            "Corrente": ["BEAM", "PILLS_METAL_COMP", "BEAM"],
            "Diagonale": ["DIAGONAL", "PILLS_METAL_COMP", "DIAGONAL"],
            "Distanziale": ["SPACER", "PILLS_METAL_COMP", "SPACER"],
            "Divisorio": ["DIVIDER", "PILLS_METAL_COMP", "DIVIDER"],
            "Fiancata laterale": ["SIDE PANEL", "PILLS_METAL_COMP", "SIDE-PANEL"],
            "Filo": ["WIRE", "PILLS_METAL_COMP", "WIRE"],
            "Frontalino": ["RISER", "PILLS_METAL_COMP", "RISER"],
            "Gancio": ["HOOK", "PILLS_METAL_COMP", "HOOK"],
            "Lamiera generica": ["SHEET METAL", "PILLS_METAL_COMP", "GENERIC SHEET METAL"],
            "Mensola": ["BRACKET", "PILLS_METAL_COMP", "BRACKET"],
            "Montante": ["UPRIGHT", "PILLS_METAL_COMP", "UPRIGHT"],
            "Pannello frontale": ["FRONT PANEL", "PILLS_METAL_COMP", "PANEL"],
            "Pannello rivestimento": ["BACK PANEL", "PILLS_METAL_COMP", "PANEL"],
            "Pedana di base": ["BASE PLATFORM", "PILLS_METAL_COMP", "BASE"],
            "Piastra di fissaggio": ["FIXING PLATE", "PILLS_METAL_COMP", "PLATE"],
            "Piede di base": ["BASE FOOT", "PILLS_METAL_COMP", "FOOT"],
            "Porta cartello": ["SIGN HOLDER", "PILLS_METAL_COMP", "SIGN HOLDER"],
            "Portaprezzo": ["TICKET-HOLDER", "PILLS_METAL_COMP", "TICKET-HOLDER"],
            "Profilo": ["PROFILE", "PILLS_METAL_COMP", "PROFILE"],
            "Protezione": ["PROTECTION FOR PERFORATED SHELF", "PILLS_METAL_COMP", "PROTECTION"],
            "Rinforzo": ["STIFFENER", "PILLS_METAL_COMP", "STIFFENER"],
            "Ripiano": ["SHELF", "PILLS_METAL_COMP", "SHELF"],
            "Staffa": ["PLATE", "PILLS_METAL_COMP", "PLATE"],
            "Tamponamento": ["BUFFER PANEL", "PILLS_METAL_COMP", "BUFFER"],
            "Traversino": ["CROSS BAR", "PILLS_METAL_COMP", "CROSS BAR"],
            "Tubolare": ["TUBULAR", "PILLS_METAL_COMP", "BAR"],
            "Vasca": ["TANK", "PILLS_METAL_COMP", "TANK"],
            "Zoccolatura": ["PLINTH", "PILLS_METAL_COMP", "PLINTH"]
        }
    },
    "WOOD COMP": {
        "macro_en": "WOOD COMPONENT",
        "Particolari": {
            "Anta/sportello": ["DOOR", "PILLS_WOOD_COMP", "DOOR"],
            "Asta in legno": ["WOODEN ROD", "PILLS_WOOD_COMP", "ROD"],
            "Cielino": ["WOODEN CANOPY", "PILLS_WOOD_COMP", "CANOPY"],
            "Compensazione": ["WOODEN FILLER PIECE", "PILLS_WOOD_COMP", "SPACER"],
            "Coprimontante": ["WOODEN UPRIGHT-COVER", "PILLS_WOOD_COMP", "COVER"],
            "Copripiede": ["WOODEN FOOT-COVER", "PILLS_WOOD_COMP", "COVER"],
            "Fiancata": ["WOODEN SIDE PANEL", "PILLS_WOOD_COMP", "SIDE PANEL"],
            "Mobiletto in legno": ["WOODEN CABINET", "PILLS_WOOD_COMP", "CABINET"],
            "Pannello in legno": ["WOODEN PANEL", "PILLS_WOOD_COMP", "PANEL"],
            "Ripiano Legno": ["WOODEN SHELF", "PILLS_WOOD_COMP", "SHELF"],
            "Schienale Legno": ["WOODEN BACK", "PILLS_WOOD_COMP", "PANEL"],
            "Tamponamento": ["BUFFER PANEL", "PILLS_WOOD_COMP", "BUFFER"],
            "Zoccolatura": ["WOODEN PLINTH", "PILLS_WOOD_COMP", "PLINTH"]
        }
    },
    "PLASTIC COMP": {
        "macro_en": "PLASTIC COMPONENT",
        "Particolari": {
            "Anta": ["DOOR", "PILLS_PLASTIC_COMP", "DOOR"],
            "Cerniera": ["HINGE", "PILLS_PLASTIC_COMP", "ACCESSORY"],
            "Divisorio": ["DIVIDER", "PILLS_PLASTIC_COMP", "DIVIDER"],
            "Frontalino": ["RISER", "PILLS_PLASTIC_COMP", "RISER"],
            "Guarnizione": ["GASKET", "PILLS_PLASTIC_COMP", "ACCESSORY"],
            "Pannello": ["PANEL", "PILLS_PLASTIC_COMP", "PANEL"],
            "Portaprezzo": ["TICKET-HOLDER", "PILLS_PLASTIC_COMP", "TICKET-HOLDER"],
            "Tappo": ["PLASTIC CAP", "PILLS_PLASTIC_COMP", "CAP"]
        }
    },
    "GLASS COMP": {
        "macro_en": "GLASS COMPONENT",
        "Particolari": {
            "Anta": ["GLASS DOOR", "PILLS_GLASS_COMP", "DOOR"],
            "Cancelletto": ["GLASS ARM", "PILLS_GLASS_COMP", "ARM"],
            "Chiusura": ["COVER", "PILLS_GLASS_COMP", "COVER"],
            "Ripiano": ["GLASS SHELF", "PILLS_GLASS_COMP", "SHELF"]
        }
    },
    "FASTENER": {
        "macro_en": "FASTENER",
        "Particolari": {
            "Bullone": ["BOLT", "PILLS_FASTNER", "FASTENER"],
            "Dado": ["NUT", "PILLS_FASTNER", "NUT"],
            "Inserti filettati": ["RIVET", "PILLS_FASTNER", "RIVET"],
            "Rondella": ["WASHER", "PILLS_FASTNER", "WASHER"],
            "Vite": ["SCREW", "PILLS_FASTNER", "SCREW"]
        }
    },
    "ASSEMBLY": {
        "macro_en": "ASSEMBLY",
        "Particolari": {
            "Avancassa": ["IMPULSE UNIT", "PILLS_ASSEMBLY", "DISPLAY"],
            "Banco espositore di legno": ["WOODEN DESK", "PILLS_ASSEMBLY", "DESK"],
            "Cassa pagamento automatico": ["SELF CHECKOUT", "PILLS_ASSEMBLY", "SELF CHECKOUT (SCO)"],
            "Cassettiera": ["CHEST OF DRAWERS", "PILLS_ASSEMBLY", "DRAWER"],
            "Controventatura": ["CROSS-BRACING", "PILLS_ASSEMBLY", "CROSS-BRACING"],
            "Espositore": ["DISPLAY", "PILLS_ASSEMBLY", "DISPLAY"],
            "Espositore a gradoni": ["STEPLADDER DISPLAY", "PILLS_ASSEMBLY", "DISPLAY"],
            "Espositore riviste": ["DISPLAY FOR MAGAZINE", "PILLS_ASSEMBLY", "DISPLAY"],
            "Spalla": ["FRAME", "PILLS_ASSEMBLY", "FRAME"],
            "Telaio saldato": ["METAL WELDMENT", "PILLS_ASSEMBLY", "FRAME"],
            "Totem": ["TOTEM", "PILLS_ASSEMBLY", "DISPLAY"],
            "Vetrina": ["SHOWCASE", "PILLS_ASSEMBLY", "SHOWCASE"]
        }
    }
}

OPZIONI_COMPATIBILITA = ["", "F25", "F25 BESPOKE", "F25 READY", "F50", "F50 BESPOKE", "F50 READY", "UNIVERSAL", "BC", "FORTISSIMO", "MINIRACK", "UNIMOB"]

MAPPA_NORMATIVE_FASTENER = {
    "Vite": {
        "": "", "DIN 912 - Testa cilindrica": "DIN 912", "DIN 933 - Esagonale filetto totale": "DIN 933",
        "DIN 931 - Esagonale filetto parziale": "DIN 931", "DIN 7991 - Testa svasata esagono incassato": "DIN 7991",
        "ISO 7380 - Testa bombata esagono incassato": "ISO 7380", "DIN 571 - Tirafondo per legno": "DIN 571",
        "DIN 7504-K - Autoperforante Esagonale": "DIN 7504-K", "DIN 7504-N - Autoperforante Bombata": "DIN 7504-N",
        "DIN 7504-P - Autoperforante Svasata": "DIN 7504-P"
    },
    "Dado": {"": "", "DIN 934 - Esagonale standard": "DIN 934", "DIN 985 - Autobloccante nylon": "DIN 985", "DIN 6923 - Flangiato zigrinato": "DIN 6923"},
    "Rondella": {"": "", "DIN 125 - Piana standard": "DIN 125", "DIN 9021 - Fascia larga": "DIN 9021", "DIN 6798 - Dentellata": "DIN 6798", "DIN 127 - Grower (elastica)": "DIN 127"},
    "Bullone": {"": ""}, "Inserti filettati": {"": ""}
}

TERMINI_ANTICIPATI = [
    "CENTRAL", "LEFT", "RIGHT", "REINFORCED", "INTERNAL", "EXTERNAL", "STATIC", "ADJUSTABLE", "SEISMIC",
    "MULTIBAR", "MULTISTRIP", "TOP", "INTER-BASE SHELF", "ROUNDED", "SLOPING", "SHAPED", "CONNECTING", "SHUTTER", "COUPLING",
    "WIRE", "GRIPPED", "CHROMED", "PAINTED", "MESH", "SLIDING", "CURVED", "STRAIGHT", "MILLING", "WIRE-BASKET",
    "SEMICIRCULAR", "SINGLE", "DOUBLE", "END", "L-SHAPED", "U-SHAPED", "SERRATED LOCK", "ROTATING", "CTR", "UPRIGHT-GRAFT"
]
